'use client';
import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    dashboard: 'Dashboard',
    billing: 'Billing',
    inventory: 'Inventory',
    customers: 'Customers',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    todaySales: "Today's Sales",
    totalDue: 'Total Due',
    lowStock: 'Low Stock Items',
    totalProducts: 'Total Products',
    salesSubtitle: 'Cash + Online payments today',
    dueSubtitle: 'Outstanding customer dues',
    stockSubtitle: 'Items below threshold',
    productSubtitle: 'Total inventory items',
    quickActions: 'Quick Actions',
    commonTasks: 'Common tasks to get started',
    generateInvoice: 'Generate new invoice',
    updateStock: 'Add or update stock',
    viewDues: 'View dues and payments',
    lowStockAlert: 'Low Stock Alert',
    restockSoon: 'items are running low. Please restock soon.',
    welcomeBack: 'Welcome back',
    addProduct: 'Add Product',
    itemName: 'Item Name',
    quantity: 'Quantity',
    rate: 'Rate',
    unit: 'Unit',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    customerName: 'Customer Name',
    mobile: 'Mobile',
    address: 'Address',
    amount: 'Amount',
    paid: 'Paid',
    due: 'Due',
    cash: 'Cash',
    online: 'Online',
    sale: 'Sale',
    purchase: 'Purchase',
    payment: 'Payment',
    expense: 'Expense',
    voiceCommand: 'Voice Command',
    manualBilling: 'Manual Billing',
    generateBill: 'Generate Bill',
    shopName: 'Shop Name',
    gstNumber: 'GST Number',
    updateSettings: 'Update Settings',
    createStaff: 'Create Staff Account',
    dayBook: 'Day Book',
    totalCash: 'Total Cash',
    totalOnline: 'Total Online',
    closingBalance: 'Closing Balance',
    viewBills: 'View Bills',
    collectPayment: 'Collect Payment',
    payerName: 'Payer Name',
    splitPayment: 'Split Payment',
    addAnotherMode: 'Add Another Mode',
    savePayment: 'Save Payment',
    totalPaying: 'Total Paying',
    notes: 'Notes',
    paymentDate: 'Payment Date',
    receipt: 'Receipt',
    date: 'Date',
    total: 'Total',
    pendingDue: 'Pending Due',
    paidFull: 'Paid Full',
    invoice: 'Invoice',
    dealerId: 'Dealer ID',
    searchPlaceholder: 'Search by name, mobile or address...',
    bankAccount: 'Bank Account',
    billingHistory: 'Billing History',
    historySubtitle: 'View and manage all bills for this customer',
    itemsLabour: 'Items & Labour',
    vehicleNo: 'Vehicle No',
    paymentDetails: 'Payment Details',
    receipt: 'Receipt',
    pay: 'Pay',
    delivered: 'Delivered',
    notDelivered: 'Not Delivered',
    paymentReceipt: 'PAYMENT RECEIPT',
    loadingCost: 'Loading Cost',
    paymentCompleted: 'Payment Completed',
    collectPayment: 'Collect Payment',
    fullDue: 'CREDIT (Full Due)',
    split: 'SPLIT',
    from: 'From',
    staff: 'Staff',
    noHistory: 'No transaction history found',
    noDues: 'No outstanding dues found! 🎉',
    outstandingDues: 'Outstanding Dues',
    duesSubtitle: 'List of customers with pending payments',
    customerBalances: 'Customer Balances',
    contact: 'Contact',
    location: 'Location',
    action: 'Action',
    details: 'Details',
    voiceAssistant: 'AI Voice Assistant',
    voiceDesc: 'बोलकर बिल बनाएं - Examples: "Raju ko 10 Urea diya 5000 mein" or "500 ka chai kharcha"',
    listening: 'Listening...',
    clickToSpeak: 'Click to speak',
    youSaid: 'You said',
    enterBillDetails: 'Enter bill details manually',
    enterShopDetails: 'Enter shop details here',
    items: 'Items',
    addItem: 'Add Item',
    addNewShop: 'Add New Shop',
    vehicleNumber: 'Vehicle No.',
    labourLoading: 'Labour/Loading',
    paymentMode: 'Payment Mode',
    paidAmount: 'Paid Amount',
    selectBank: 'Select Bank',
    saveBill: 'Save Bill',
    totalAmount: 'Total Amount',
    optional: 'Optional',
    enterShopName: 'Enter shop name',
    enterGst: 'Enter GST number (optional)',
    enterDealerId: 'Enter Dealer ID',
    enterMobile: 'Mobile number',
    enterAddress: 'Shop address',
    addShop: 'Add Shop',
    loading: 'Loading...',
    deliveredQuestion: 'Delivered?',
    yes: 'Yes',
    no: 'No',
    totalBill: 'Total Bill',
    howToPay: 'How would you like to pay?',
    splitPaymentQuestion: 'Split Payment?',
    selectAccount: 'Select Account',
    bankAccountName: 'Bank Account Name',
    onlineAccount: 'Online Account',
    addNewBank: 'Add New Bank Account',
    payingNow: 'Paying Now',
    fullPaymentQuestion: 'Full payment?',
    fullCashNote: 'Full amount will be marked as CASH',
    enterPayerName: 'Enter payer name',
    enterAccountName: 'Enter account name',
    amountToPay: 'Amount to pay',
    addMode: 'Add Mode',
    fromPayer: 'From Account Name',
    billInvoice: 'Bill/Invoice',
    amountPaid: 'Amount Paid',
    creating: 'Creating...',
    saveBill: 'Save Bill',
    fromHolder: 'From (Account Holder Name)',
    addAnotherMethod: 'Add Another Payment Method',
    addAccount: 'Add Account',
    accountNumber: 'Account Number',
    ifscCode: 'IFSC Code',
    upiId: 'UPI ID',
    enterBankDetails: 'Enter bank account or wallet details',
    editProduct: 'Edit Product',
    addNewProduct: 'Add New Product',
    companyName: 'Company Name',
    stockQuantity: 'Stock quantity',
    price: 'Price',
    threshold: 'Low Stock Alert Threshold',
    alertBelow: 'Alert when below',
    searchInventory: 'Search products by name or company...',
    clearFilter: 'Clear Low Stock Filter',
    noProducts: 'No products added yet',
    totalStock: 'Total Stock',
    actions: 'Actions',
    companyBrand: 'Company / Brand',
    currentStock: 'Current Stock',
    totalValue: 'Total Value',
    deleteConfirm: 'Are you sure you want to delete this product?',
    productUpdated: 'Product updated!',
    productAdded: 'Product added!',
    productDeleted: 'Product deleted!',
    selectDateRange: 'Select date range to view transactions',
    startDate: 'Start Date',
    endDate: 'End Date',
    exportCsv: 'Export CSV',
    transactionHistory: 'Transaction History',
    found: 'found',
    noTransactions: 'No transactions found for this date range',
    walkIn: 'Walk-in',
    note: 'Note',
    reportExported: 'Report exported!',
    fullCredit: 'CREDIT (FULL DUE)',
    manageShop: 'Manage your shop configuration and staff',
    shopConfig: 'Shop Configuration',
    updateShopDetails: 'Update your shop details (appears on invoice)',
    enterYourShopName: 'Your shop name',
    gstOptional: 'GST Number (optional)',
    shopAddress: 'Shop address',
    logoUrlOptional: 'Logo URL (Optional)',
    updating: 'Updating...',
    staffManagement: 'Staff Management',
    manageStaffAccounts: 'Create and manage staff accounts',
    createNewStaffAccount: 'Create New Staff Account',
    enterStaffName: 'Staff name',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    staffMembers: 'Staff Members',
    accountInfo: 'Account Information',
    role: 'Role',
    settingsUpdated: 'Settings updated successfully!',
    failedUpdateSettings: 'Failed to update settings',
    staffCreated: 'Staff account created successfully!',
    failedCreateStaff: 'Failed to create staff account',
    noCustomersMatch: 'No customers match your search',
    clear: 'Clear',
    paidFull: 'Paid full',
    posSystem: 'Smart POS system for fertilizer shops',
    smartBilling: 'Smart Billing',
    fastBilling: 'Fast POS billing with PDF invoice generation',
    stockTracking: 'স্টॉक ट्रैकिंग with low stock alerts',
    dueTracking: 'Due tracking made easy',
    builtWith: 'Built with ❤️ for fertilizer shop owners',
    createBill: 'Create Bill',
    manageInventory: 'Manage Inventory',
    customerLedger: 'Customer Ledger',
    failedFetchCustomers: 'Failed to fetch customers',
    customerAdded: 'Customer added!',
    failedAddCustomer: 'Failed to add customer',
    errorAddingCustomer: 'Error adding customer',
    failedLoadHistory: 'Failed to load history',
    failedFetchSettings: 'Failed to fetch settings',
    errorUpdatingSettings: 'Error updating settings',
    errorCreatingStaff: 'Error creating staff account'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    billing: 'बिलिंग',
    inventory: 'स्टॉक',
    customers: 'ग्राहक',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग',
    logout: 'लॉगआउट',
    todaySales: 'आज की बिक्री',
    totalDue: 'कुल उधार',
    lowStock: 'कम स्टॉक',
    totalProducts: 'कुल उत्पाद',
    salesSubtitle: 'आज का कुल नकद और ऑनलाइन भुगतान',
    dueSubtitle: 'ग्राहकों का कुल बकाया उधार',
    stockSubtitle: 'थ्रेशोल्ड से कम मात्रा वाली वस्तुएं',
    productSubtitle: 'इन्वेंट्री में कुल उत्पादों की संख्या',
    quickActions: 'त्वरित कार्रवाई',
    commonTasks: 'शुरू करने के लिए सामान्य कार्य',
    generateInvoice: 'नया चालान (Inoice) बनाएं',
    updateStock: 'स्टॉक जोड़ें या अपडेट करें',
    viewDues: 'उधार और भुगतान देखें',
    lowStockAlert: 'कम स्टॉक अलर्ट',
    restockSoon: 'वस्तुएं कम हो रही हैं। कृपया जल्द ही स्टॉक भरें।',
    welcomeBack: 'स्वागत है',
    addProduct: 'उत्पाद जोड़ें',
    itemName: 'वस्तु का नाम',
    quantity: 'मात्रा',
    rate: 'दर',
    unit: 'इकाई',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    edit: 'संपादित',
    delete: 'हटाएं',
    customerName: 'ग्राहक का नाम',
    mobile: 'मोबाइल',
    address: 'पता',
    amount: 'राशि',
    paid: 'भुगतान किया',
    due: 'बकाया',
    cash: 'नकद',
    online: 'ऑनलाइन',
    sale: 'बिक्री',
    purchase: 'खरीद',
    payment: 'भुगतान',
    expense: 'खर्च',
    voiceCommand: 'आवाज कमांड',
    manualBilling: 'मैनुअल बिलिंग',
    generateBill: 'बिल बनाएं',
    shopName: 'दुकान का नाम',
    gstNumber: 'जीएसटी नंबर',
    updateSettings: 'सेटिंग अपडेट करें',
    createStaff: 'स्टाफ अकाउंट बनाएं',
    dayBook: 'रोजनामचा',
    totalCash: 'कुल नकद',
    totalOnline: 'कुल ऑनलाइन',
    closingBalance: 'अंतिम शेष',
    viewBills: 'बिल देखें',
    collectPayment: 'पेमेंट लें',
    payerName: 'पेमेंट करने वाले का नाम',
    splitPayment: 'स्प्लिट पेमेंट',
    addAnotherMode: 'अन्य मोड जोड़ें',
    savePayment: 'पेमेंट सेव करें',
    totalPaying: 'कुल भुगतान',
    notes: 'नोट्स',
    paymentDate: 'भुगतान की तारीख',
    receipt: 'रसीद',
    date: 'तारीख',
    total: 'कुल',
    pendingDue: 'बकाया उधार',
    paidFull: 'पूरा भुगतान',
    invoice: 'चालान (Invoice)',
    dealerId: 'डीलर ID',
    searchPlaceholder: 'नाम, मोबाइल या पते से खोजें...',
    bankAccount: 'बैंक खाता',
    billingHistory: 'बिलिंग इतिहास',
    historySubtitle: 'इस ग्राहक के सभी बिल देखें और प्रबंधित करें',
    itemsLabour: 'सामान और मजदूरी',
    vehicleNo: 'गाड़ी नंबर',
    paymentDetails: 'भुगतान का विवरण',
    receipt: 'रसीद',
    pay: 'भुगतान',
    delivered: 'डिलीवर हो गया',
    notDelivered: 'डिलीवर नहीं हुआ',
    paymentReceipt: 'भुगतान रसीद',
    loadingCost: 'लोडिंग चार्ज',
    paymentCompleted: 'भुगतान पूरा हुआ',
    collectPayment: 'पेमेंट लें',
    fullDue: 'पूर्ण उधार (Full Due)',
    split: 'स्प्लिट',
    from: 'के द्वारा',
    staff: 'स्टाफ',
    noHistory: 'कोई लेनदेन इतिहास नहीं मिला',
    noDues: 'कोई बकाया उधार नहीं मिला! 🎉',
    outstandingDues: 'कुल बकाया उधार',
    duesSubtitle: 'लंबित भुगतान वाले ग्राहकों की सूची',
    customerBalances: 'ग्राहकों का बकाया शेष',
    contact: 'संपर्क',
    location: 'स्थान',
    action: 'कार्रवाई',
    details: 'विवरण',
    voiceAssistant: 'AI आवाज सहायक',
    voiceDesc: 'बोलकर बिल बनाएं - उदाहरण: "राजू को 10 यूरिया दिया 5000 में"',
    listening: 'सुन रहा हूँ...',
    clickToSpeak: 'बोलने के लिए क्लिक करें',
    youSaid: 'आपने कहा',
    enterBillDetails: 'बिल विवरण मैनुअल भरें',
    enterShopDetails: 'दुकान का विवरण यहाँ भरें',
    items: 'सामान',
    addItem: 'सामान जोड़ें',
    addNewShop: 'नई दुकान जोड़ें',
    vehicleNumber: 'गाड़ी नंबर',
    labourLoading: 'मजदूरी/लोडिंग',
    paymentMode: 'भुगतान का मोड',
    paidAmount: 'भुगतान राशि',
    selectBank: 'बैंक चुनें',
    saveBill: 'बिल सेव करें',
    totalAmount: 'कुल राशि',
    optional: 'वैकल्पिक',
    enterShopName: 'दुकान का नाम भरें',
    enterGst: 'जीएसटी नंबर भरें (वैकल्पिक)',
    enterDealerId: 'डीलर ID भरें',
    enterMobile: 'मोबाइल नंबर',
    enterAddress: 'दुकान का पता',
    addShop: 'दुकान जोड़ें',
    loading: 'लोड हो रहा है...',
    deliveredQuestion: 'डिलीवरी हुई?',
    yes: 'हाँ',
    no: 'नहीं',
    totalBill: 'कुल बिल',
    howToPay: 'आप भुगतान कैसे करना चाहेंगे?',
    splitPaymentQuestion: 'स्प्लिट पेमेंट?',
    selectAccount: 'खाता चुनें',
    bankAccountName: 'बैंक खाते का नाम',
    onlineAccount: 'ऑनलाइन खाता',
    addNewBank: 'नया बैंक खाता जोड़ें',
    payingNow: 'अभी भुगतान',
    fullPaymentQuestion: 'पूरा भुगतान?',
    fullCashNote: 'पूरी राशि नकद (CASH) मानी जाएगी',
    enterPayerName: 'पेमेंट करने वाले का नाम लिखें',
    enterAccountName: 'खाते का नाम लिखें',
    amountToPay: 'भुगतान राशि',
    addMode: 'मोड जोड़ें',
    fromPayer: 'पेमेंट करने वाले का नाम',
    billInvoice: 'बिल/चालान',
    amountPaid: 'भुगतान की गई राशि',
    creating: 'बनाया जा रहा है...',
    saveBill: 'बिल सेव करें',
    fromHolder: 'के द्वारा (खाताधारक का नाम)',
    addAnotherMethod: 'एक और भुगतान मोड जोड़ें',
    addAccount: 'खाता जोड़ें',
    accountNumber: 'खाता नंबर',
    ifscCode: 'IFSC कोड',
    upiId: 'UPI ID',
    enterBankDetails: 'बैंक खाते या वॉलेट का विवरण भरें',
    editProduct: 'उत्पाद संपादित करें',
    addNewProduct: 'नया उत्पाद जोड़ें',
    companyName: 'कंपनी का नाम',
    stockQuantity: 'स्टॉक मात्रा',
    price: 'कीमत',
    threshold: 'कम स्टॉक अलर्ट थ्रेशोल्ड',
    alertBelow: 'अलर्ट जब इससे कम हो',
    searchInventory: 'नाम या कंपनी से स्टॉक खोजें...',
    clearFilter: 'कम स्टॉक फिल्टर हटाएं',
    noProducts: 'अभी तक कोई उत्पाद नहीं जोड़ा गया है',
    totalStock: 'कुल स्टॉक',
    actions: 'कार्रवाई',
    companyBrand: 'कंपनी / ब्रांड',
    currentStock: 'वर्तमान स्टॉक',
    totalValue: 'कुल मूल्य',
    deleteConfirm: 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं?',
    productUpdated: 'उत्पाद अपडेट हो गया!',
    productAdded: 'उत्पाद जुड़ गया!',
    productDeleted: 'उत्पाद हटा दिया गया!',
    selectDateRange: 'लेनदेन देखने के लिए तारीख सीमा चुनें',
    startDate: 'शुरूआती तारीख',
    endDate: 'अंतिम तारीख',
    exportCsv: 'CSV एक्सपोर्ट करें',
    transactionHistory: 'लेनदेन इतिहास',
    found: 'मिले',
    noTransactions: 'इस तारीख सीमा के लिए कोई लेनदेन नहीं मिला',
    walkIn: 'आम ग्राहक',
    note: 'नोट',
    reportExported: 'रिपोर्ट एक्सपोर्ट हो गई!',
    fullCredit: 'पूर्ण उधार (FULL DUE)',
    manageShop: 'दुकान की सेटिंग्स और स्टाफ प्रबंधित करें',
    shopConfig: 'दुकान का विन्यास (Configuration)',
    updateShopDetails: 'अपनी दुकान का विवरण अपडेट करें (चालान पर दिखता है)',
    enterYourShopName: 'अपनी दुकान का नाम',
    gstOptional: 'जीएसटी नंबर (वैकल्पिक)',
    shopAddress: 'दुकान का पता',
    logoUrlOptional: 'लोगो URL (वैकल्पिक)',
    updating: 'अपडेट हो रहा है...',
    staffManagement: 'स्टाफ प्रबंधन',
    manageStaffAccounts: 'स्टाफ अकाउंट बनाएं और प्रबंधित करें',
    createNewStaffAccount: 'नया स्टाफ अकाउंट बनाएं',
    enterStaffName: 'स्टाफ का नाम',
    name: 'नाम',
    email: 'ईमेल',
    password: 'पासवर्ड',
    staffMembers: 'स्टाफ सदस्य',
    accountInfo: 'खाता जानकारी',
    role: 'भूमिका (Role)',
    settingsUpdated: 'सेटिंग्स सफलतापूर्वक अपडेट हो गईं!',
    failedUpdateSettings: 'सेटिंग्स अपडेट करने में विफल',
    staffCreated: 'स्टाफ अकाउंट सफलतापूर्वक बन गया!',
    failedCreateStaff: 'स्टाफ अकाउंट बनाने में विफल',
    noCustomersMatch: 'आपकी खोज से कोई ग्राहक नहीं मिला',
    clear: 'साफ (Clear)',
    paymentReceipt: 'भुगतान रसीद',
    paidFull: 'पूरा भुगतान',
    posSystem: 'खाद दुकान के लिए स्मार्ट POS सिस्टम',
    smartBilling: 'स्मार्ट बिलिंग',
    fastBilling: 'PDF रसीद के साथ तेज़ बिलिंग',
    stockTracking: 'कम स्टॉक अलर्ट के साथ स्टॉक ट्रैकिंग',
    dueTracking: 'उधारी का हिसाब हुआ आसान',
    builtWith: 'खाद दुकानदारों के लिए ❤️ के साथ बनाया गया',
    createBill: 'बिल बनाएं',
    manageInventory: 'स्टॉक प्रबंधन',
    customerLedger: 'ग्राहक खाता',
    failedFetchCustomers: 'ग्राहक लोड करने में विफल',
    customerAdded: 'ग्राहक जोड़ा गया!',
    failedAddCustomer: 'ग्राहक जोड़ने में विफल',
    errorAddingCustomer: 'ग्राहक जोड़ने में त्रुटि',
    failedLoadHistory: 'इतिहास लोड करने में विफल',
    failedFetchSettings: 'सेटिंग्स लोड करने में विफल',
    errorUpdatingSettings: 'सेटिंग्स अपडेट करने में त्रुटि',
    errorCreatingStaff: 'स्टाफ अकाउंट बनाने में त्रुटि'
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('hi');

  useEffect(() => {
    const saved = localStorage.getItem('language');
    if (saved) setLanguage(saved);
  }, []);

  const toggleLanguage = () => {
    const newLang = language === 'en' ? 'hi' : 'en';
    setLanguage(newLang);
    localStorage.setItem('language', newLang);
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
